### ISSUE TITLE
css-loader incorrectly process escaped characters within the content CSS property

### ISSUE THREAD

**Issue by andreypopp** [webpack/css-loader#87]
Repro: https://gist.github.com/andreypopp/e3a8f338d21b1b4eebd2

Bootstrap has the following glyphicon class definition, `bootstrap/dist/css/bootstrap.css`:
```
.glyphicon-plus:before {
  content: "\2b";
}
```
which is processed by webpack into `bundle.js`:
```
.glyphicon-plus:before{content:"2b"}
```

So instead of the icon I see "2b" in the browser.

Note that other icons with escape codes like:
```
.glyphicon-pencil:before {
  content: "\270f";
}
.glyphicon-glass:before {
  content: "\e001";
}
```
are processed just fine.

**Comment by andreypopp** [comment]
Also note that I'm not sure if shorthand escape codes are valid in CSS so that might be a bug in Twitter Bootstrap instead.

**Comment by mathieumg** [comment]
I imagine this is from master? If this is from 0.15.1, it might already be fixed. See https://github.com/webpack/css-loader/issues/79 There has been no new tag since.

**Comment by andreypopp** [comment]
@markdalgleish I get version of `css-selector-tokenizer@0.5.2` with fixes for #79 but the I reported issue still manifests itself. Also reproducible with `css-loader` from `master`.

**Comment by JackVCurtis** [comment]
I got this to work by changing css-selector-tokenizer/parseValues.js, line 26.
Was: `return content.replace(/\\([a-fA-F0-9]{4}|.)/g, function(escaped) {`
Fixed: `return content.replace(/\\([a-fA-F0-9]{2,4}|.)/g, function(escaped) {`

Although rather than edit the library, it's probably easier to override glyphicon-asterisk and glyphicon-plus. These work fine:

```
.glyphicon-asterisk               { &:before { content: "\002a"; } }
.glyphicon-plus                   { &:before { content: "\002b"; } }
```

**Comment by andreypopp** [comment]
I'd rather make sure `css-loader` works with bootstrap (and probably with other CSS as two-char-escape codes seems like a thing) out of the box. Let's create a pull request!

**Comment by JackVCurtis** [comment]
Oh, definitely fix the loader. I was just going to use the second fix until the pull request is closed. I spent way too much time today thinking I wasn't loading fonts correctly...

**Comment by chandlervdw** [comment]
@sokra I am still having this issue, even though I've got `css-selector-tokenizer` v0.5.4...
